services:
    odoo_web:
        image: odoo:16
        container_name: document-approval
        ports:
            - 8069:8069
        volumes:
            - odoo-web-data:/var/lib/odoo
            - ./addons:/mnt/extra-addons
            - ./file-storage:/etc/file-storage
        depends_on:
            - db
        networks:
            - odoo-network

    db:
        image: postgres:15
        container_name: db-document-approval
        ports:
            - 5432:5432
        volumes:
            - odoo-db-data:/var/lib/postgresql/data/pgdata
        networks:
            - odoo-network
        environment:
            - POSTGRES_USER=odoo
            - POSTGRES_PASSWORD=odoo
            - POSTGRES_DB=postgres
            - PGDATA=/var/lib/postgresql/data/pgdata
volumes:
    odoo-web-data:
    odoo-db-data:

networks:
    odoo-network:
        name: odoo-network
